_target_: src.models.motivation_interview_module.MILitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.attention_models.SA_SACA

# compile model for faster training with pytorch 2.0
compile: false

class_weights: 6.0
